# Generated by Django 4.2 on 2023-04-03 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rezervace', '0003_hodnoceni_pobytu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hodnoceni_pobytu',
            options={'ordering': ['nazev_ubytovani', 'klient'], 'verbose_name': 'Hodnocení pobytu', 'verbose_name_plural': 'Hodnocení pobytů'},
        ),
    ]
